apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vinokrish001
  template:
    metadata:
      labels:
        app: vinokrish001
    spec:
      containers:
        - name: vinokrish001
          image: icr.io/vinokrish001/personalexpense
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: vinokrish001
  type: NodePort
  ports:
    - port: 5000
      nodePort: 31514
